### ISSUE TITLE
Fluix cables disappear

### ISSUE THREAD

**Issue by solovenko-v** [SanAndreasP/ImmersiveCables#11]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.2.2]

What version of MinecraftForge do you use?
[14.23.1.2582]

What version of Immersive Engineering do you use?
[0.12 - 76]

What version of Immersive Cables do you use?
[1.2.0.1]
 
What is the issue / bug you have encountered? Give us a short description.
[Fluix cables disappear]

How can it be reproduced?
[Connect the ME Drive to a **working** ME Controller. The cable will disappear after a few seconds. (Appliedenergistics2-rv5-stable-4)] 

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[no log file]

**Comment by SanAndreasP** [comment]
why no log file?

**Comment by SanAndreasP** [comment]
Also can you provide some screenshots of your setup?

Does the drive still connect to the network (just the cables disappear)?

**Comment by SanAndreasP** [comment]
given no answer for over a month, I assume this issue is not existing anymore, thus I'll close it now. If it's still an issue, please open a new one **_and provide logs_**
