### ISSUE TITLE
Cable Render Issue with Latest IE Wire Changes

### ISSUE THREAD

**Issue by Voxel-Friend** [SanAndreasP/ImmersiveCables#12]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[14.23.1.2607]

What version of Immersive Engineering do you use?
[0.12-78]

What version of Immersive Cables do you use?
[1.2.0.1]
 
What is the issue / bug you have encountered? Give us a short description.
[
![2018-02-26_23 58 09](https://user-images.githubusercontent.com/12395262/36713091-76895dc4-1b51-11e8-9b8c-5934c560d2eb.png)
(Note - the two relays are connected to each other, and the two transformers are linked. using retextured refined storage module)
]

How can it be reproduced?
[Load game with above mod versions, use with refined storage to load RS module, connect relays and transformers together with relevant wires. Not sure if issue is the same with AE2 module, but chances are, with latest wire code changes, this will be the case as well.]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[https://gist.github.com/Voxel-Friend/0bc8b66f5d4a011f72bdaaadbcb1bc99]

**Comment by Voxel-Friend** [comment]
It should be noted that this issue is resolved during rollback of IE to version 0.12-77

**Comment by SanAndreasP** [comment]
Visuals are fixed now in 1.3.0.
You can download it on CurseForge once they approved the file.

**Comment by Voxel-Friend** [comment]
Thank you for your prompt and excellent work!
