### ISSUE TITLE
Fluix wire coils often yields "Connection is obstructed" message on valid connections

### ISSUE THREAD

**Issue by Nerodon** [SanAndreasP/ImmersiveCables#17]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.4.2703

What version of Immersive Engineering do you use?
0.12-82

What version of Immersive Cables do you use?
1.12.2-1.3.0
 
What is the issue / bug you have encountered? Give us a short description.
Many placements for both fluix and dense fluix relays yields only obstructed errors when trying to connect them to any other relay. There doesn't seem to be a pattern but some specific coordinates always gives obstructed errors.

It's not so obvious to reproduce but most often happens underground, below Y64, testing in natural caves is easy enough to find a placement where the relays are considered obstructed. Happens in both single player and on dedicated servers.

![image](https://user-images.githubusercontent.com/12401473/41887364-4e88a58e-78ce-11e8-86ba-dc41485325d3.png)

How can it be reproduced?
-Start a new game in creative
-find an underground cave system ( I found a large natural cave at Y30s or so)
-place 2 fluix relays next to each other and try to connect them with a fluix wire coil
-if the error does not occur, move to a different area and try again till the error occurs

The bug does not occur everywhere, it seems related to the coord more than what is around it, sometimes it could take me several attempts over 100 blocks distance until I reproduced the bug

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:

No logs are explicitely generated during the event of the bug, no errors/exceptions
https://gist.github.com/Nerodon/2adbd637ba56017de9e2ade035f87482
Logs where I start finding the error: [22:28:21]

**Comment by SanAndreasP** [comment]
Does this also happen with IE copper wires at the exact same locations?

**Comment by Nerodon** [comment]
I tried IE wires and they work fine.
Only the fluix and dense fluix are giving me trouble (did not test fiber cables).

Also in some cases, fluix wires can be connected through solid walls, maybe the raytrace/ canSee function in wireCoil.java returns incorrect results?

**Comment by Nerodon** [comment]
![image](https://user-images.githubusercontent.com/12401473/41951429-e6d085bc-7998-11e8-94ee-5c664d61240b.png)

**Comment by Nerodon** [comment]
I managed to track down the issue, looked at IE's code on their latest build and found a discrepancy.
I made pull request with the appropriate changes for the wire obstruction detection to work properly.

Tested it locally, works like a charm now.

**Comment by SanAndreasP** [comment]
Alright, I've updated the mod now, it should be available (alongside with a couple of other fixes) once Curse approves the file here: https://minecraft.curseforge.com/projects/immersive-cables/files/2579102
