### ISSUE TITLE
Refined transformer crash when on server

### ISSUE THREAD

**Issue by gt22** [SanAndreasP/ImmersiveCables#20]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
4.23.4.2739

What version of Immersive Engineering do you use?
0.12-84

What version of Immersive Cables do you use?
1.3.1
 
What is the issue / bug you have encountered? Give us a short description.
When logging on server, after placing `Refined Transformer` client instantly crashes

How can it be reproduced?
1. Build simple refined stroage network (Just controller should be enough, in my setup it was controller, crafting grid and drive with one 16k disk)
2. Connect transformer to the controller
3. Connect another transformer to isolated crafting grid
4. Wire them together
5. Exit from server, and join again 

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/gt22/4264c9461933bb54dc9d441f8af4c3e5 - crash log
https://gist.github.com/gt22/49a9a3b1b253053559ef090558316601 - latest log

**Comment by SanAndreasP** [comment]
I fixed it now, you download the new version once approved here: https://minecraft.curseforge.com/projects/immersive-cables/files/2595013
