### ISSUE TITLE
Unloading and relaoding a chunk causes cables to detach from cable connectors

### ISSUE THREAD

**Issue by GanaramInukshuk** [SanAndreasP/ImmersiveCables#4]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[14.23.1.2570]

What version of Immersive Engineering do you use?
[0.12-75]

What version of Immersive Cables do you use?
[1.0.0]
 
What is the issue / bug you have encountered? Give us a short description.
[Unloading and reloading a chunk causes cables to detach from cable connectors; chunkloaded chunks are unaffected; may also affect Refined Storage's corresponding cable but was unable to check due to not having RS installed]

How can it be reproduced?
[Connect cables to cable connectors, walk away far enough for chunks to unload, and return. Video provided also: https://youtu.be/qxou-87VAGI
]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[https://gist.github.com/GanaramInukshuk/5446663535639e72895efd8f5c51c585]

**Comment by SanAndreasP** [comment]
hm, I can see what's causing it. Lemme check that.
