### ISSUE TITLE
Applied llamagistics support?

### ISSUE THREAD

**Issue by lolorz13** [SanAndreasP/ImmersiveCables#9]
Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[Forge 14.23.1.2582]

What version of Immersive Engineering do you use?
[0.12-75]

What version of Immersive Cables do you use?
[1.2.0.1]
 
What is the issue / bug you have encountered? Give us a short description.
IC currently does not support Applied llamagistics and crashes with an error related to smart dense cables. Will IC support Applied llamagistics in the future?

How can it be reproduced?
Install IE, IC, Applied llamagistics, and proceed to launch

link to log file:
https://gist.github.com/lolorz13/06bc0454cbcfe35ab34655fe0c8794a0

**Comment by SanAndreasP** [comment]
Interesting... even though AL is a separate mod, they use the same Mod ID and packages...
I'd say it's an issue with AL, given AE changed some bits of their API, so I suggest report it there.

**Comment by SanAndreasP** [comment]
I've created a new issue on the Applied Llamagistics repo myself now.
